import { Bot } from "lucide-react";

interface AIExplanationProps {
  explanation: string;
}

export default function AIExplanation({ explanation }: AIExplanationProps) {
  const bullets = [
    { label: "Analysis", detail: explanation || "Loading explanation..." },
  ];

  return (
    <div className="bg-white border border-border rounded-xl shadow-sm p-5 flex flex-col h-full relative overflow-hidden">
      <div className="absolute top-0 left-0 bottom-0 w-1 bg-primary rounded-l-xl" />

      <div className="flex items-center gap-3 mb-4">
        <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
          <Bot className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-text-primary leading-none mb-0.5">AI Explanation</h3>
          <span className="text-[10px] text-text-muted">Generated by prediction model</span>
        </div>
      </div>

      <div className="flex-1 flex flex-col gap-3">
        {bullets.map((b) => (
          <div key={b.label} className="flex gap-2.5">
            <p className="text-xs text-text-secondary leading-relaxed font-light">{b.detail}</p>
          </div>
        ))}
      </div>

      <div className="mt-4 pt-3 border-t border-border-light flex items-center justify-between text-[10px] text-text-muted font-mono">
        <span>Model v2.1</span>
      </div>
    </div>
  );
}
